services:
  - type: web
    name: aquagestion-frontend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://aquagestion-backend.onrender.com/api
      - key: NODE_ENV
        value: production
